### ISSUE TITLE
Android app not building when upgrading from 1.1.0 to 4.0.6 [🐛] 

### ISSUE THREAD

**Issue by ralphhovsepian** [react-native-image-picker/react-native-image-picker#1794]
### Description

Explain the bug in as much detail as possible
I am trying to upgrade the library from 1.1.0 to 4.0.6. My react native version is 0.63.3. When i am trying to do `npm run android`. I am getting this error. But the app is running normally on ios. 

I have checked my enviroment setup, tried cleaning gradle, cleaning cache.

```
> Task :app:compileDebugJavaWithJavac FAILED
406 actionable tasks: 2 executed, 404 up-to-date
C:\Users\Ralph\Desktop\workspace\mentorcliq-mobile\android\app\src\main\java\com\mentorcliq\Linking\LinkingModule.java:23: error: cannot find symbol
import com.imagepicker.FileProvider;
                      ^
  symbol:   class FileProvider
  location: package com.imagepicker
C:\Users\Ralph\Desktop\workspace\mentorcliq-mobile\android\app\src\main\java\com\mentorcliq\Linking\LinkingModule.java:93: error: cannot find symbol
            Uri fileUri = FileProvider.getUriForFile(getReactApplicationContext(),
                          ^
  symbol:   variable FileProvider
  location: class LinkingModule
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors


* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### How to repeat issue and example

1. have your react native version 0.63.3
2. have your react-native-image-picker version 4.0.76 (upgrading from 1.1.0)
3. run `npm run android`

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [4.0.6]
- React Native version: [0.63.3]
- Platform: [Android]
- Development Operating System: [Windows]
- Dev tools: [Android SDK version target 29. minimum: 21] navigation crash for Android

**Comment by joumanam** [comment]
I'm having the same issue, were you able to fix it?

**Comment by MursiDirect** [comment]
Same Issue here, Any solution please? @ralphhovsepian

**Comment by asadhmeedrunn** [comment]
same here
