### ISSUE TITLE
[🐛] cannot find symbol import androidx.activity.result.PickVisualMediaRequest;

### ISSUE THREAD

**Issue by Alexufo** [react-native-image-picker/react-native-image-picker#2356]
### Description

On compile 
react-native-image-picker\android\src\main\java\com\imagepicker\ImagePickerModuleImpl.java:27: error: cannot find symbol
import androidx.activity.result.PickVisualMediaRequest;
                               ^
  symbol:   class PickVisualMediaRequest
  location: package androidx.activity.result

![Image](https://github.com/user-attachments/assets/60fa1dc6-af55-4b00-a30a-87c2b997d67f)

### Additional Information

- Image Picker version: 8.0.0
- React Native version: 0.72.9
- Platform: android
- Development Operating System:  windows

**Comment by ozgurrgul** [comment]
Same issue.

Image Picker version: 8.0.0
React Native version: 0.72.13
Platform: android
Development Operating System: macOs

Gradle:

```
dependencies {
    // ..omitted..
    implementation 'androidx.activity:activity:1.9.3'
    implementation 'androidx.activity:activity-ktx:1.9.3'
}
```

<img width="840" alt="Image" src="https://github.com/user-attachments/assets/4558d331-d4af-4f0c-b8ae-c9f896b80cec" />

**Comment by Alexufo** [comment]
I started using the latest version of `npx react-native-builder-bob@latest init` and the error disappeared with version 8.0.0.

**Comment by devaniumesh** [comment]
I have same issue after upgrade from 5.6.1, Please update version in gradle file of your library asap.

![Image](https://github.com/user-attachments/assets/14a18e67-255d-4d5c-80ae-2fe663589ed8)

**Comment by SabrioBiblio** [comment]
The same problem. Is there a solution?
